"""Core schemas for emltriage."""

from emltriage.core.models import (
    AnalysisMode,
    Artifacts,
    AttachmentEntry,
    AttachmentHash,
    AuthDomainResult,
    AuthResult,
    AuthenticationResults,
    BodyEntry,
    CaseMetadata,
    FileManifestEntry,
    HeaderEntry,
    IOCEntry,
    IOCsExtracted,
    IOCType,
    Manifest,
    RiskReason,
    RiskScore,
    RoutingHop,
    Severity,
    URLEntry,
)

__all__ = [
    "AnalysisMode",
    "Artifacts",
    "AttachmentEntry",
    "AttachmentHash",
    "AuthDomainResult",
    "AuthResult",
    "AuthenticationResults",
    "BodyEntry",
    "CaseMetadata",
    "FileManifestEntry",
    "HeaderEntry",
    "IOCEntry",
    "IOCsExtracted",
    "IOCType",
    "Manifest",
    "RiskReason",
    "RiskScore",
    "RoutingHop",
    "Severity",
    "URLEntry",
]
